const INITIALIZATION_SUCCESS = "social/app/INITIALIZE-SUCCESS";
const ADD_NOTIFICATION = "social/app/ADD-NOTIFICATION";
const REMOVE_NOTIFICATION = "social/app/REMOVE-NOTIFICATION";

export default {
    INITIALIZATION_SUCCESS,
    ADD_NOTIFICATION,
    REMOVE_NOTIFICATION
}